# Site settings
title: "Mobile Intelligence Laboratory"
description: "Mirae Hall #122/#327, SEOULTECH, Republic of Korea"
baseurl: ""
url: "https://mint-lab.github.io"

# Social profile
# email: ""
github_username: "mint-lab"
# twitter_username: ""

# Build settings
markdown: "kramdown"

# Other options
# permalink: "blog/:year/:month/:title"
# job.title: ""
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
